site:
  title: Redpanda Docs
  start_page: ROOT:introduction:intro-to-events.adoc
  url: http://localhost:8000
content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/JakeSCahill/docs-site
    branches: main
    start_paths: [site-search, home, api]
ui:
  bundle:
    url: https://github.com/JakeSCahill/redpanda-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - 'node_modules/antora-extensions-and-macros/macros/glossary.js'
  - 'node_modules/antora-extensions-and-macros/macros/config-ref.js'
  - 'node_modules/antora-extensions-and-macros/macros/helm-ref.js'
antora:
  extensions:
  - 'node_modules/antora-extensions-and-macros/extensions/unlisted-pages.js'
  - require: 'node_modules/antora-extensions-and-macros/extensions/add-global-attributes.js'
    org: JakeSCahill
    repo: docs-site
    branch: main

